version: '3'
services:
  mongo-db:
    container_name: mongo-db-container
    image: mongo:6.0.6
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  api:
    container_name: api-container
    build: .
    image: clean-node-api
    restart: always
    command: yarn debug
    volumes:
      - ./dist/:/usr/src/clean-node-api/dist/
      - ./keys/:/usr/src/clean-node-api/keys/
      - ./package.json:/usr/src/clean-node-api/package.json
      - ./.env:/usr/src/clean-node-api/.env
    ports: 
      - "5050:5050"
      - "9222:9222"
    links:
      - mongo-db