name: CI/CD

on:
  push:
    branches:
      - main
      - 'releases/**'

jobs:
  cicd:
    runs-on: ubuntu-20.04
    container: cypress/base
    steps:
      - name: Setup
        run: |
          apt update
          apt -y install ca-certificates
          apt -y install curl
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'
      - name: Install
        run: yarn install
      - name: Test
        run: |
          yarn eslint 'src/**'
          yarn test:ci
      - name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Trigger deployment
        env:
          DEPLOY_HOOK_URL: ${{ secrets.DEPLOY_HOOK_URL }}
        run: |
          curl $DEPLOY_HOOK_URL
